### PR TITLE
Use the deployment_status workflow trigger.

### PR DESCRIPTION
**Pull request by mikenikles**

### CODE REVIEW

**Comment by mikenikles** [comment]
`curl -v https://api.github.com/repos/mikenikles/www-mikenikles-com/deployments/238645649/statuses` lists the deployments for this PR - looks good.

**TODO**: Use `target_url` in my workflow file rather than `environment_url`. Only `target_url` seems available in the `curl` request above.

**Comment by arunoda** [comment]
Hey @mikenikles,

This is great work.
I work on Vercel.

We only set `environment_url` only when the deployment status is "success".
Also, I think you need to use `application/vnd.github.ant-man-preview+json` [`Accept` header](https://developer.github.com/v3/repos/deployments/#get-a-deployment-status) to get the `environment_url`.

**Comment by mikenikles** [comment]
Thanks @arunoda. I'm trying to trigger my GitHub Actions workflow in this PR with the `on: deployment_status` trigger once Vercel deployed my preview app.

It seems the Vercel GitHub app does not trigger that event. Could you let me know if Vercel triggers this event: https://help.github.com/en/actions/reference/events-that-trigger-workflows#deployment-status-event-deployment_status?

At https://vercel.com/docs/v2/git-integrations/vercel-for-github, in the "Extending Your GitHub Workflow" chapter, it says "Due to using GitHub's Deployments API, you will also be able to integrate with other services through GitHub's checks. Vercel will provide the deployment URL to the checks that require it, for example; to a testing suite such as Checkly."
This makes me believe I should use https://help.github.com/en/actions/reference/events-that-trigger-workflows#check-run-event-check_run. If that's the case, how can I access the deployment URL?

**Comment by arunoda** [comment]
> It seems the Vercel GitHub app does not trigger that event. Could you let me know if Vercel triggers this event: https://help.github.com/en/actions/reference/events-that-trigger-workflows#deployment-status-event-deployment_status?

Yes. We do that for sure.

Don't use check run. We don't attach the actual URL to that. Only the Vercel dashboard URL.

**Pull request closed without merging**
